url: https://aptanadev.github.io
baseurl: ""

# Site settings
title: Jaya Abadi
email: support@mydomain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Lindawati 
  pic: 1
  position: Sales & Marketing

- name: Yuliana
  pic: 2
  position: Accounting & Finance

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/jayaabadisolo

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
